# Mandatory first line to specify API version.
# Ideally always use the latest version, typically 3 or higher.
version: "3.5"

# Define the different microservices.
services:

  # Web frontend/app.
  web-fe:
    build: .
    # Entry point.
    command: python app.py
    ports:
      - target: 5000
        published: 5001
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /code

  # Redis cache.
  redis:
    image: "redis:alpine"
    networks:
      counter-net:

# Creates new networks
# By default it creates a `bridge` network to connect multiple containers on
# the same Docker host.
networks:
  counter-net:

volumes:
  counter-vol:
